# Generated by Django 6.0.2 on 2026-03-02 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_no', models.IntegerField(blank=True, null=True)),
                ('house_name', models.CharField(blank=True, max_length=120, null=True)),
                ('street', models.CharField(blank=True, max_length=120, null=True)),
                ('town', models.CharField(blank=True, max_length=50, null=True)),
                ('post_code', models.CharField(blank=True, max_length=12, null=True)),
                ('date_field', models.DateField(blank=True, db_column='date_', null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('courier_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'courier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('nam_identifier', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'names',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PostOfficeSales',
            fields=[
                ('office_date', models.DateField(blank=True, null=True)),
                ('post_office_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_class_stamp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sec_class_stamp', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('letters_postage_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('standard_parcel', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('next_day_parcel', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('tot_kg_price', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'post_office_sales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('prices_pk', models.AutoField(primary_key=True, serialize=False)),
                ('first_cl_stamp', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sec_cl_stamp', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('post_letter', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('standard_parcel', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('next_day_parcel', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('prices_fk', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('quantity_pk', models.AutoField(primary_key=True, serialize=False)),
                ('date_field', models.DateField(blank=True, db_column='date_', null=True, unique=True)),
                ('first_cl_stamp', models.IntegerField()),
                ('sec_cl_stamp', models.IntegerField()),
                ('post_letter', models.IntegerField()),
                ('standard_parcel', models.IntegerField()),
                ('next_day_parcel', models.IntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'quantity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('letters_pk', models.AutoField(primary_key=True, serialize=False)),
                ('letter_sent', models.DateField(blank=True, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=20, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ThePostOfficeApp.address')),
            ],
            options={
                'db_table': 'letters',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='address',
            name='nam_identifier',
            field=models.ForeignKey(blank=True, db_column='nam_identifier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ThePostOfficeApp.names'),
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('parcels_pk', models.AutoField(primary_key=True, serialize=False)),
                ('parcel_sent', models.DateField(blank=True, null=True)),
                ('service', models.CharField(blank=True, max_length=8, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ThePostOfficeApp.address')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ThePostOfficeApp.courier')),
            ],
            options={
                'db_table': 'parcels',
                'managed': True,
            },
        ),
    ]
